syntax = "proto3";

package tieba;

option java_package = "com.huanchengfly.tieba.post.api.models.protos";

import "AdInfo.proto";
import "Abstract.proto";
import "Agree.proto";
import "AlaLiveInfo.proto";
import "AnchorInfo.proto";
import "Baijiahao.proto";
import "DealInfo.proto";
import "DislikeInfo.proto";
import "HeadItem.proto";
import "HotTWThreadInfo.proto";
import "Item.proto";
import "Lbs.proto";
import "Media.proto";
import "MultipleForum.proto";
import "OriginThreadInfo.proto";
import "PbContent.proto";
import "PbLinkInfo.proto";
import "PollInfo.proto";
import "Post.proto";
import "SimpleForum.proto";
import "SkinInfo.proto";
import "TailInfo.proto";
import "TiebaPlusAd.proto";
import "TogetherHi.proto";
import "User.proto";
import "VideoInfo.proto";
import "Voice.proto";
import "VoiceRoom.proto";
import "Zan.proto";
import "ZhiBoInfoTW.proto";

message ThreadInfo {
  int64 id = 1;
  int64 threadId = 2;
  string title = 3;
  int32 replyNum = 4;
  int32 viewNum = 5;
  string lastTime = 6;
  int32 lastTimeInt = 7;
  int32 threadTypes = 8;
  int32 isTop = 9;
  int32 isGood = 10;
  int32 is_vote = 11;
  int32 is_voice_thread = 15;
  User author = 18;
  User lastReplyer = 19;
  int32 commentNum = 20;
  repeated Abstract _abstract = 21;
  repeated Media media = 22;
  repeated Voice voice_info = 23;
  int32 thread_type = 26;
  int64 forumId = 27;
  string forumName = 28;
  int32 is_livepost = 30;
  int32 isNoTitle = 38;
  int32 is_bub = 39;
  int64 firstPostId = 40;
  Zan zan = 41;
  int32 is_global_top = 42;
  int32 is_pic = 43;
  int32 createTime = 45;
  int32 repost_num = 46;
  int32 has_commented = 48;
  string from = 49;
  int32 collectStatus = 50;
  string collectMarkPid = 51;
  int64 post_id = 52;
  int32 time = 53;
  int32 isMemberTop = 54;
  AnchorInfo anchor_info = 55;
  int64 authorId = 56;
  uint32 valid_post_num = 57;
  uint32 is_ad = 59;
  string pids = 61;
  Lbs location = 62;
  uint32 timeline = 64;
  int32 hot_weight = 66;
  int32 storecount = 68;
  int32 post_num = 69;
  HotTWThreadInfo hotTWInfo = 71;
  ZhiBoInfoTW twzhibo_info = 72;
  string category_name = 73;
  PollInfo poll_info = 74;
  int32 is_novel = 76;
  optional VideoInfo videoInfo = 79;
  uint32 pic_num = 84;
  repeated TailInfo ext_tails = 90;
  TogetherHi high_together = 95;
  int32 is_deal = 97;
  DealInfo deal_info = 98;
  SkinInfo skin_info = 100;
  string recom_source = 104;
  string recom_weight = 105;
  uint64 last_read_pid = 106;
  string recom_reason = 109;
  AdInfo video_ad_info = 110;
  repeated PbContent richTitle = 111;
  repeated PbContent richAbstract = 112;
  optional AlaLiveInfo ala_info = 113;
  repeated DislikeInfo dislikeInfo = 120;
  repeated MultipleForum multiple_forum_list = 122;
  int32 is_multiforum_thread = 123;
  int32 agreeNum = 124;
  Post top_agree_post = 125;
  Agree agree = 126;
  int32 is_partial_visible = 127;
  int64 freq_num = 130;
  int32 is_god = 131;
  Media pic_info = 133;
  int64 shareNum = 135;
  OriginThreadInfo origin_thread_info = 141;
  repeated PbContent firstPostContent = 142;
  int32 is_share_thread = 143;
  uint64 trans_num = 145;
  int32 isTopic = 148;
  string topicUserName = 149;
  string topicH5Url = 150;
  SimpleForum forumInfo = 155;
  string tShareImg = 159;
  int32 is_bjh = 161;
  string nid = 164;
  int32 is_headlinepost = 165;
  Baijiahao baijiahao = 169;
  string thread_share_link = 172;
  int32 if_comment = 173;
  int32 tabId = 175;
  string tabName = 176;
  repeated PbLinkInfo pb_link_info = 178;
  Item item = 179;
  repeated HeadItem item_star = 180;
  int32 isDeleted = 181;
  int32 hotNum = 182;
  uint32 collect_num = 190;
  TiebaPlusAd tiebaplus_ad = 201;
  int32 is_pictxt = 204;
  int32 is_highlight = 213;
  int32 is_excellent_thread = 219;
  repeated Post hot_post_list = 221;
  string head_type = 227;
  int64 disable_share = 228;
  string share_url = 230;
  int64 top_thread_set_time = 231;
}